### ISSUE TITLE
Ethernet not working

### ISSUE THREAD

**Issue by adebmbng** [remorses/catalina-hackintosh#1]
Hi,

First, thank you for your EFI. It's working fine.
but i have an issue with ethernet from this motherboard.

do you have the solution for ethernet?

**Comment by Ru-C** [comment]
Hi there, thanks for sharing your EFI. I have the same problem with lack of onboard Ethernet. Catalina wont install as the OSX Installer says an Internet connection is needed.

**Comment by adebmbng** [comment]
Hi @Ru-C ,

I found the solution. 
first you need to update some of item of your clover
and make sure you check your bios setting.

**Comment by Ru-C** [comment]
Hi @adebmbng , thanks the reply. I am quite new to this ! Could you either send me a plist file, or explain what I need to change? Also what BIOS settings do I need to adjust? Thanks for your help !
